version: "3"

tasks:
  dev:
    cmds:
      - air
  docs:
    cmds:
      - swag init --dir ./cmd/http,./internal/todo
  build:
    cmds:
      - go build -o http-server cmd/http/main.go
  start:
    cmds:
      - ./http-server
  install:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/go-task/task/v3/cmd/task@latest
