import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: restaurants } = api.restaurants.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hej</h1>
        {!restaurants ? "no data" : restaurants[0]?.address.city}
        <pre>{JSON.stringify(restaurants, null, 2)}</pre>
      </main>
    </>
  );
};

export default Home;
